name: memolog_new
description: "A new Flutter project for diary log."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase dependencies to compatible versions
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.3.0

  # Cupertino Icons for iOS-specific icons
  cupertino_icons: ^1.0.8

  # Optional: State management solution
  provider: ^6.0.4
  table_calendar: ^3.1.2
  logger: ^2.5.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package to encourage best coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/leather_diary.png
  # Add any additional assets or fonts as needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
