name: memolog_new
description: "A new Flutter project for diary log."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (ensuring compatibility)
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.3.0

  # Icons for iOS-specific usage
  cupertino_icons: ^1.0.8

  # Additional dependencies
  provider: ^6.0.4 # For state management
  table_calendar: ^3.1.2 # For calendar functionality
  logger: ^2.5.0 # For debugging/logging
  image_picker: ^1.1.2 # For attaching images

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for best practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (ensuring path correctness)
  assets:
    - lib/images/leather_diary.png

# Uncomment the fonts section if you plan to use custom fonts
# fonts:
#   - family: Roboto
#     fonts:
#       - asset: fonts/Roboto-Regular.ttf
#       - asset: fonts/Roboto-Bold.ttf
