name: memolog_new
description: "A new Flutter project for diary log."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (ensure compatibility)
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7

  # Icons for iOS-specific usage
  cupertino_icons: ^1.0.8

  # Additional dependencies
  provider: ^6.0.4 # For state management
  table_calendar: ^3.1.2 # For calendar functionality
  logger: ^2.5.0 # For debugging/logging
  image_picker: ^1.1.2 # For attaching images
  firebase_app_check: ^0.3.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for best practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/images/leather_diary.png
