// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQthl5w2R46nYndj_FNdgMeHfWrQRN6E',
    appId: '1:89543923187:web:447316b80c180e55d86e86',
    messagingSenderId: '89543923187',
    projectId: 'memolog-new',
    authDomain: 'memolog-new.firebaseapp.com',
    storageBucket: 'memolog-new.firebasestorage.app',
    measurementId: 'G-7HVV1GJSYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvMSuwJ3i529ZVejAJmzzoRFTSrBiSwvY',
    appId: '1:89543923187:android:2b4107925ef8954ad86e86',
    messagingSenderId: '89543923187',
    projectId: 'memolog-new',
    storageBucket: 'memolog-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCbeLA28mQZljqgsVPsS0MGk7nmZT-jf4',
    appId: '1:89543923187:ios:cea621657341ac5ed86e86',
    messagingSenderId: '89543923187',
    projectId: 'memolog-new',
    storageBucket: 'memolog-new.firebasestorage.app',
    iosBundleId: 'com.example.memologNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCbeLA28mQZljqgsVPsS0MGk7nmZT-jf4',
    appId: '1:89543923187:ios:cea621657341ac5ed86e86',
    messagingSenderId: '89543923187',
    projectId: 'memolog-new',
    storageBucket: 'memolog-new.firebasestorage.app',
    iosBundleId: 'com.example.memologNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOQthl5w2R46nYndj_FNdgMeHfWrQRN6E',
    appId: '1:89543923187:web:301aefda454c9a6cd86e86',
    messagingSenderId: '89543923187',
    projectId: 'memolog-new',
    authDomain: 'memolog-new.firebaseapp.com',
    storageBucket: 'memolog-new.firebasestorage.app',
    measurementId: 'G-MD54ZZT6X6',
  );
}
